apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fleetman-hpa
spec:
   scaleTargetRef:
     apiVersion: apps/v1
     kind: Deployment
     name: position-tracker
   minReplicas: 1
   maxReplicas: 5
   targetCPUUtilizationPercentage: 70